# This is a basic workflow to help you get started with Actions

name: Deploy Virtual Machine

# Controls when the action will run. 
on: 
  # 手動ワークフロー トリガー
  workflow_dispatch:
    # ワークフロー実行時に使用するパラメーターを定義
    inputs:
      # パラメーター名
      resourceGroupName: 
        # ワークフロー実行時に画面に表示される名前
        description: Resource Group Name
        # 入力を必須に指定
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # ジョブの名前はメンバーで重複しないように指定
  deploy-virtual-machine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 登録したシークレットで Azure へログイン
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure CLI を使用し ARM テンプレートから仮想マシンを展開
      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          # {parameter file} には先の手順で作成したパラメーター ファイル名を指定
          inlineScript: |
            az deployment group create --resource-group ${{ github.event.inputs.resourceGroupName }} --template-file ./Hands-on-Lab/templates/deploy-vm-as-domain-member.json --parameters ./Hands-on-Lab/templates/deploy-vm-as-domain-member.parameters.json

      # ログアウト
      - name: Azure logout
        run: |
          az logout